name             'libguestfs'
maintainer       'Engine Yard, Inc.'
maintainer_email 'cookbooks@engineyard.com'
license          'Apache 2.0'
description      'Installs/Configures libguestfs'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.2'
recipe           'libguestfs', 'Installs guestfs libraries and tools'
recipe           'libguestfs::dev', 'Installs guestfs development libraries'
recipe           'libguestfs::erlang', 'Installs guestfs erlang bindings'
recipe           'libguestfs::python', 'Installs guestfs python bindings'
recipe           'libguestfs::ruby', 'Installs guestfs ruby bindings'

supports 'amazon'
supports 'debian'
supports 'centos'
supports 'fedora'
supports 'redhat'
supports 'ubuntu'

depends 'apt'
