---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04-i386_chef-11.4.4.box
  run_list:
  - recipe[apt]
  - recipe[test_helper::fix_permissions]
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
  run_list:
  - recipe[test_helper::fix_permissions]

suites:
- name: basic
  run_list: 
  - recipe[minitest-handler]
  - recipe[app_test::basic]
