# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.hostname = "oihdohd-berkshelf"
  config.vm.box = "precise64"
  config.berkshelf.enabled = true
  config.vm.provision :chef_solo do |chef|
    chef.json = {
      :mysql => {
        :server_root_password => 'rootpass',
        :server_debian_password => 'debpass',
        :server_repl_password => 'replpass'
      },
      :beaver => {
        :ssh_generate_keypair => true,
        :configuration => {
	  :ssh_tunnel => 'logging@192.168.1.9',
	  :ssh_tunnel_port => 6379,
	  :ssh_remote_host => '127.0.0.1',
	  :ssh_remote_port => 6379,
	  :transport => 'redis',
	  :redis_url => 'redis://127.0.0.1:6379/0',
	  :redis_namespace => 'logstash:beaver'
	}
      }
    }

    chef.run_list = [
   	"recipe[python]",
        "recipe[beaver]"
    ]
  end
end
