name              "ckbk"
maintainer        "Fletcher Nichol"
maintainer_email  "fnichol@nichol.ca"
license           "Apache 2.0"
description       "A sweet, do-nothing cookbook for tooling testing"
long_description  "A sweet, do-nothing cookbook for tooling testing"
version           "0.2.4"
