set_unless[:piwik][:version] = "1.5.1"
set_unless[:piwik][:install_path] = "/var/www"

set_unless[:piwik][:php_fcgi_memory_limit] = "128M"
set_unless[:piwik][:php_fcgi_children] = "5"
set_unless[:piwik][:php_fcgi_max_requests] = "1000"
set_unless[:piwik][:php_fcgi_bind_path] = "/tmp/.php-fcgi-socket"
set_unless[:piwik][:php_fcgi_pass] = "unix:/tmp/.php-fcgi-socket"

# Params used in slave recipe only:
set_unless[:piwik][:config][:superuser][:login] = "override_attribute in role!"
set_unless[:piwik][:config][:superuser][:password] = "override_attribute in role!"
set_unless[:piwik][:config][:superuser][:email] = "override_attribute in role!"
set_unless[:piwik][:config][:superuser][:salt] = "override_attribute in role!"
set_unless[:piwik][:config][:database][:host] = "localhost"
set_unless[:piwik][:config][:database][:port] = "3306"
set_unless[:piwik][:config][:database][:username] = "piwik"
set_unless[:piwik][:config][:database][:password] = "override_attribute in role!"
set_unless[:piwik][:config][:database][:dbname] = "piwik"
set_unless[:piwik][:config][:database][:adapter] = "PDO_MYSQL"
set_unless[:piwik][:config][:database][:tables_prefix] = "piwik_"
set_unless[:piwik][:config][:database][:charset] = "utf8"
