maintainer       "Vitaly dark_dr4g0n Shishlyannikov"
maintainer_email "dark.dr4g0n@gmail.com"
license          "Apache 2.0"
description      "Installs iftop"
version          "0.0.1"
supports	 "debian, ubuntu"
