maintainer       "nagalakshmi_n"
maintainer_email "nagalakshmi.n@cloudenablers.com"
license          "Apache 2.0"
description      "Installs/Configures SugarCRM Community Edition"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "1.0"
depends          "php"
depends          "apache2"
depends          "mysql"
depends          "openssl"
depends          "git"
