source 'https://rubygems.org'

gem 'chef', '~>11.4.4'
gem 'foodcritic'
gem 'knife-ec2', '~>0.6.4'
gem 'test-kitchen', '=1.0.0.beta.3'
gem 'kitchen-ec2', '=0.6.0'
gem 'kitchen-vagrant', :group => :integration
gem "minitest-chef-handler", "~> 1.0.1"
gem 'berkshelf'
gem 'chefspec'
gem 'aws-sdk'
