maintainer       "Guilhem Lettron"
maintainer_email "guilhem.lettron@youscribe.com"
name             "pgbadger"
license          "Apache 2.0"
description      "Install pgbadger"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.2"
depends          "apt"
supports         "ubuntu"
recipe           "install", "Install pgbadger on the node"
