---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_provisionerless.box
- name: opscode-debian-7.1.0
  driver_config:
    box: opscode-debian-7.1.0
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_debian-7.1.0_provisionerless.box
- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
- name: centos-5.9
  driver_config:
    box: opscode-centos-5.9
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-5.9_provisionerless.box
# Fails on python setup.py install.
#- name: gentoo
#  driver_config:
#   box: gentoo
#   box_url: https://lxmx-vm.s3.amazonaws.com/vagrant/boxes/lxmx_gentoo-2013.05_chef-11.4.4.box
#- name: scientific-linux-6-x64
#  driver_config:
#    box: scientific-linux-6-x64
#    box_url: http://download.frameos.org/sl6-64-chefclient-0.10.box
## Arch missing wget or curl. Need arch box with wget/curl installed.
#- name: arch-linux
#  driver_config:
#    box: archlinux
#    box_url: http://iweb.dl.sourceforge.net/project/vagrantarchlinx/2011.08.19/archlinux_2011.08.19.box
- name: opensuse-12.1
  driver_config:
    box: opensuse-12.1-x64
    box_url: https://s3.amazonaws.com/circlejtp/OpenSuseVagrant/OpenSuse12_1x64_July14.box
#- name: freebsd-9.1
#  driver_config:
#    box: freebsd-9.1-amd64
#    box_url: https://s3.amazonaws.com/vagrant_boxen/freebsd_amd64_ufs.box 

suites:
- name: default
  run_list: ["recipe[amazon_s3cmd::source]"]
  attributes: {}
